- name: build env
  hosts: 'build'
  become: true

  tasks:
  - name: install default-jdk
    apt:
      name: 'default-jdk'
      state: present

  - name: install maven
    apt:
      name: 'maven'
      state: present

  - name: install git
    apt:
      name: 'git'
      state: present

  - name: download project from git-а
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: '/opt/app'

  - name: package проект
    shell: mvn clean package
    args:
      chdir: '/opt/app'

  - name: get war-file
    fetch:
      src: '/opt/app/target/hello-1.0.war'
      dest: '/opt/app/hello-1.0.war'
      flat: yes

- name: PROD env
  hosts: 'prod'
  become: true

  tasks:

  - name: Install tomcat
    apt:
      name: 'tomcat9'
      state: present

  - name: Copy webapp-file
    copy:
      src: '/opt/app/hello-1.0.war'
      dest: '/var/lib/tomcat9/webapps/hello-1.0.war'

  - name: Start tomcat
    service:
      name: 'tomcat9'
      state: started