- name: Сборочное окружение
  hosts: 'build'
  become: true

  tasks:
  - name: Установка default-jdk
    apt:
      name: 'default-jdk'
      state: present

  tasks:
  - name: Установка maven
    apt:
      name: 'maven'
      state: present

  tasks:
  - name: Установка git
    apt:
      name: 'git'
      state: present

  - name: Скачиваем проект из git-а
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: '/opt/app'

  - name: Собираем проект
    shell: mvn clean package
    args:
      chdir: '/opt/app'

- name: Прод окружение
  hosts: 'prod'
  become: true

  tasks:

  - name: Установка tomcat
    apt:
      name: 'tomcat9'
      state: present

  - name: Копирование war-файла
    copy:
      src: '/opt/app/target/hello-1.0.war'
      dest: '/var/lib/tomcat9/webapps/hello-1.0.war'

  - name: Запуск tomcat
    service:
      name: 'tomcat9'
      state: started